config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: 'home#index'

  resources :users, only: [:new, :create]

  resources :servers, only: [:index, :show]

  resources :account, only: :index

  resources :home, only: :index

  resources :install, only: :index
end

app/views/layouts/nav_bar/_top_nav.html.erb
<%=content_tag :nav, class: "navbar navbar-expand-sm navbar-dark bg-dark" do%>
  <%=content_tag :nav, class: "container-fluid" do%>
    <%=link_to "MC Admin", root_path, class: "navbar-brand"%>
    <%=button_tag type: "button", class: "navbar-toggler", data: {bs_toggle: "collapse", bs_target: "#navbarSupportedContent"}, aria_controls: "navbarSupportedContent", aria_expanded: "false", aria_label: "Toggle navigation" do%>
      <span class="navbar-toggler-icon"></span>
    <%end%>
    <%=content_tag :div, class: "collapse navbar-collapse", id: "navbarSupportedContent" do%>
      <%=content_tag :div, class: "navbar-nav me-auto mb-2 mb-lg-0" do%>
        <%=link_to "Home", root_path, class: "nav-link"%>
        <%=link_to "Install", install_index_path, class: "nav-link"%>
        <% if user_signed_in? %>
          <%=link_to "Servers", servers_path, class: "nav-link"%>
          <%=link_to "Account", account_index_path, class: "nav-link"%>
        <%end%>
      <%end%>
      <%=content_tag :div, class: "navbar-nav ms-auto mb-2 mb-lg-0" do%>
        <% unless user_signed_in? %>
          <%=form_with url: new_user_session_path, method: :get, class: "me-auto" do |form| %>
            <%=form.submit "Login", class: "ms-auto btn btn-success"%>
          <%end%>
        <%else%>
          <%=form_with url: destroy_user_session_path, method: :delete, class: "me-auto" do |form| %>
            <%=form.submit "Logout", class: "ms-auto btn btn-danger"%>
          <%end%>
        <%end%>
      <%end%>
    <%end%>
  <%end%>
<%end%>