config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: 'home#index'

  resources :users, only: [:new, :create]

  resources :servers, only: [:index, :show]

  resources :account, only: :index

  resources :home, only: :index

  resources :install, only: :index
end

app/models/server.rb
class Server < ApplicationRecord
  has_many :player_servers, dependent: :destroy
  has_many :players, through: :player_servers, inverse_of: :servers
  #has_many :players, -> { select('players.*, player_servers.status as status, player_servers.banned as banned, player_servers.updated_at as last_seen') }, through: :player_servers
  has_many :server_roles, dependent: :destroy
  has_many :users, through: :server_roles, inverse_of: :servers

  validates :name, presence: true

  def owner
    return User.find(self.server_roles.where(role: :owner).pluck(:id))
  end

  def online_player_count
    return self.player_servers.where(status: :online).count
  end
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  layout :default_layout

  before_action :authenticate_user!
  before_action :authorize_server

  def index
    @servers = current_user.servers
    respond_to do |format|
      format.html
    end
  end

  def show
    @all_attributes = @server.player_servers.collect{|ps| [ps.player_id, {status: ps.status, banned: ps.banned, last_seen: ps.updated_at}]}.to_h
    @players = @server.players
  end

private
  def authorize_server
    case params[:action].to_sym
    when :new
      @server = Server.new
    when :create
      @server = Server.new(permitted_attributes(Server.new))
    when :show, :update
      @server = Server.find(params[:id])
    end
    authorize (@server || Server)
  end
end

app/views/servers/_index.html.erb
<%=content_tag :ul, class: "list-group" do%>
  <%=content_tag :li, class: "list-group-item" do%>
    <%=content_tag :div, class: "row" do%>
      <%=content_tag :div, "Server Name", class: "col-10"%>
      <%=content_tag :div, "Online Player Count", class: "col-2"%>
    <%end%>
  <%end%>
  <%=render partial: "index_row", collection: @servers, as: :server%>
<%end%>

app/views/servers/_index_row.html.erb
<%=content_tag :li, class: "list-group-item list-group-item-action", onclick: "window.location.href = '#{server_path(server)}'" do%>
  <%=content_tag :div, class: "row" do%>
    <%=content_tag :div, server.name, class: "col-10"%>
    <%=content_tag :div, server.online_player_count, class: "col-2"%>
  <%end%>
<%end%>

app/views/servers/_player_row.html.erb
<% @p_attrs = @all_attributes[player.id] %>
<% status = @p_attrs[:status].to_sym == :online ? true : false %>
<% banned = @p_attrs[:banned].to_sym == :true ? true : false %>
<%=content_tag :li, class: "list-group-item list-group-item-action" do%>
  <%=content_tag :div, class: "row" do%>
    <%=content_tag :div, player.username, class: "col-4"%>
    <%=content_tag :div, (status ? "Online" : "Offline"), class: "col-3"%>
    <%=content_tag :div, (status ? "Now" : @p_attrs[:last_seen]), class: "col-3"%>
    <%=content_tag :div, (banned ? "Yes" : "No"), class: "col-2"%>
  <%end%>
<%end%>

app/views/servers/_players_section.html.erb
<%=content_tag :ul, class: "list-group" do%>
  <%=content_tag :li, class: "list-group-item" do%>
    <%=content_tag :div, class: "row" do%>
      <%=content_tag :div, "Username", class: "col-4"%>
      <%=content_tag :div, "Status", class: "col-3"%>
      <%=content_tag :div, "Last Seen", class: "col-3"%>
      <%=content_tag :div, "Banned?", class: "col-2"%>
    <%end%>
  <%end%>
  <%=render partial: "player_row", collection: @players, as: :player%>
<%end%>

app/views/servers/index.html.erb
<%=content_tag :h2, "Your Servers"%>
<%#=render layout: "index/index" do%>
<%=render partial: "index"%>
<%#end%>

app/views/servers/show.html.erb
<%=content_tag :h2, @server.name%>
<%=render partial: "players_section"%>